### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by SSaeki-jp** [SSaeki-jp/furima-29261#11]
## 自身のフリマアプリのURL
https://furima-29261.herokuapp.com/

## Basic認証のIDとパスワード
ID：admin
パスワード：2222

## 出品者用のメールアドレスとパスワード
メールアドレス：aa@aa
パスワード：123asd123

## 購入者用のメールアドレスとパスワード
メールアドレス：bb@bb
パスワード：123asd123

## 購入用カード（テスト）の番号・期限・セキュリティコード
番号：4242424242424242
期限：3月／23年
セキュリティコード：123

**Comment by tech-taro** [comment]
SSaeki-jpさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、完成要件は全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしていただきたく存じます。（提出はしなくて大丈夫です。）
・商品削除機能の確認
購入済みの商品を削除しようとするとエラーになる

※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。

**Comment by SSaeki-jp** [comment]
ご確認いただきまして有難うございました！引き続き学習を頑張りたいと思います！
（追記：購入済み商品の削除エラーについてハンドリングし、デプロイも完了しました）
